//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Departure information for affinity shopping requests.
 * 
 * <p>Java class for AffinityDepRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AffinityDepRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Country" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CountryType" minOccurs="0"/&gt;
 *         &lt;element name="CountrySubDivision" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CountrySubDivisionType" minOccurs="0"/&gt;
 *         &lt;element name="DateTimeFrom" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DateTimeType" minOccurs="0"/&gt;
 *         &lt;element name="DateTimeTo" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DateTimeType" minOccurs="0"/&gt;
 *         &lt;element name="ProximityDistanceMeasure" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}MeasureType" minOccurs="0"/&gt;
 *         &lt;element name="Station" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}StationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AffinityDepRequestType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "country",
    "countrySubDivision",
    "dateTimeFrom",
    "dateTimeTo",
    "proximityDistanceMeasure",
    "station"
})
public class AffinityDepRequestType2 {

    @XmlElement(name = "Country")
    protected CountryType2 country;
    @XmlElement(name = "CountrySubDivision")
    protected CountrySubDivisionType2 countrySubDivision;
    @XmlElement(name = "DateTimeFrom")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeFrom;
    @XmlElement(name = "DateTimeTo")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeTo;
    @XmlElement(name = "ProximityDistanceMeasure")
    protected MeasureType2 proximityDistanceMeasure;
    @XmlElement(name = "Station")
    protected StationType2 station;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CountryType2 }
     *     
     */
    public CountryType2 getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryType2 }
     *     
     */
    public void setCountry(CountryType2 value) {
        this.country = value;
    }

    /**
     * Gets the value of the countrySubDivision property.
     * 
     * @return
     *     possible object is
     *     {@link CountrySubDivisionType2 }
     *     
     */
    public CountrySubDivisionType2 getCountrySubDivision() {
        return countrySubDivision;
    }

    /**
     * Sets the value of the countrySubDivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountrySubDivisionType2 }
     *     
     */
    public void setCountrySubDivision(CountrySubDivisionType2 value) {
        this.countrySubDivision = value;
    }

    /**
     * Gets the value of the dateTimeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeFrom() {
        return dateTimeFrom;
    }

    /**
     * Sets the value of the dateTimeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeFrom(XMLGregorianCalendar value) {
        this.dateTimeFrom = value;
    }

    /**
     * Gets the value of the dateTimeTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeTo() {
        return dateTimeTo;
    }

    /**
     * Sets the value of the dateTimeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeTo(XMLGregorianCalendar value) {
        this.dateTimeTo = value;
    }

    /**
     * Gets the value of the proximityDistanceMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType2 }
     *     
     */
    public MeasureType2 getProximityDistanceMeasure() {
        return proximityDistanceMeasure;
    }

    /**
     * Sets the value of the proximityDistanceMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType2 }
     *     
     */
    public void setProximityDistanceMeasure(MeasureType2 value) {
        this.proximityDistanceMeasure = value;
    }

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link StationType2 }
     *     
     */
    public StationType2 getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link StationType2 }
     *     
     */
    public void setStation(StationType2 value) {
        this.station = value;
    }

}
