//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Carrier Offers grouping of Offers returned by a single ORA.
 * 
 * <p>Java class for CarrierOffersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarrierOffersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ALaCarteOffer" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ALaCarteOfferType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CarrierOffersSummary" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}OffersSummaryType" minOccurs="0"/&gt;
 *         &lt;element name="Offer" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}NewOfferType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PriceCalendar" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PriceCalendarType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarrierOffersType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "aLaCarteOffer",
    "carrierOffersSummary",
    "offer",
    "priceCalendar"
})
public class CarrierOffersType2 {

    @XmlElement(name = "ALaCarteOffer")
    protected List<ALaCarteOfferType2> aLaCarteOffer;
    @XmlElement(name = "CarrierOffersSummary")
    protected OffersSummaryType2 carrierOffersSummary;
    @XmlElement(name = "Offer")
    protected List<NewOfferType2> offer;
    @XmlElement(name = "PriceCalendar")
    protected List<PriceCalendarType2> priceCalendar;

    /**
     * Gets the value of the aLaCarteOffer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aLaCarteOffer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getALaCarteOffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ALaCarteOfferType2 }
     * 
     * 
     */
    public List<ALaCarteOfferType2> getALaCarteOffer() {
        if (aLaCarteOffer == null) {
            aLaCarteOffer = new ArrayList<ALaCarteOfferType2>();
        }
        return this.aLaCarteOffer;
    }

    /**
     * Gets the value of the carrierOffersSummary property.
     * 
     * @return
     *     possible object is
     *     {@link OffersSummaryType2 }
     *     
     */
    public OffersSummaryType2 getCarrierOffersSummary() {
        return carrierOffersSummary;
    }

    /**
     * Sets the value of the carrierOffersSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffersSummaryType2 }
     *     
     */
    public void setCarrierOffersSummary(OffersSummaryType2 value) {
        this.carrierOffersSummary = value;
    }

    /**
     * Gets the value of the offer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewOfferType2 }
     * 
     * 
     */
    public List<NewOfferType2> getOffer() {
        if (offer == null) {
            offer = new ArrayList<NewOfferType2>();
        }
        return this.offer;
    }

    /**
     * Gets the value of the priceCalendar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceCalendar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceCalendar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceCalendarType2 }
     * 
     * 
     */
    public List<PriceCalendarType2> getPriceCalendar() {
        if (priceCalendar == null) {
            priceCalendar = new ArrayList<PriceCalendarType2>();
        }
        return this.priceCalendar;
    }

}
