//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Change Order Choice
 * 
 * <p>Java class for ChangeOrderChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeOrderChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="AcceptCancelledOffer" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AcceptCancelOfferType"/&gt;
 *         &lt;element name="AcceptChange" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}SelectedOrderItemType"/&gt;
 *         &lt;element name="AcceptOrderItemList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AcceptOrderItemListType"/&gt;
 *         &lt;element name="AcceptRepricedOrder" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AcceptRepricedOrderType"/&gt;
 *         &lt;element name="AcceptSelectedQuotedOfferList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AcceptSelectedQuotedOfferListType"/&gt;
 *         &lt;element name="CancelUnpaidOrder" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CancelUnpaidOrderType"/&gt;
 *         &lt;element name="UpdatePax" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}OrderChangeUpdatePaxType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeOrderChoiceType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "acceptCancelledOffer",
    "acceptChange",
    "acceptOrderItemList",
    "acceptRepricedOrder",
    "acceptSelectedQuotedOfferList",
    "cancelUnpaidOrder",
    "updatePax"
})
public class ChangeOrderChoiceType2 {

    @XmlElement(name = "AcceptCancelledOffer")
    protected AcceptCancelOfferType2 acceptCancelledOffer;
    @XmlElement(name = "AcceptChange")
    protected SelectedOrderItemType2 acceptChange;
    @XmlElement(name = "AcceptOrderItemList")
    protected AcceptOrderItemListType2 acceptOrderItemList;
    @XmlElement(name = "AcceptRepricedOrder")
    protected AcceptRepricedOrderType2 acceptRepricedOrder;
    @XmlElement(name = "AcceptSelectedQuotedOfferList")
    protected AcceptSelectedQuotedOfferListType2 acceptSelectedQuotedOfferList;
    @XmlElement(name = "CancelUnpaidOrder")
    protected CancelUnpaidOrderType2 cancelUnpaidOrder;
    @XmlElement(name = "UpdatePax")
    protected OrderChangeUpdatePaxType2 updatePax;

    /**
     * Gets the value of the acceptCancelledOffer property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptCancelOfferType2 }
     *     
     */
    public AcceptCancelOfferType2 getAcceptCancelledOffer() {
        return acceptCancelledOffer;
    }

    /**
     * Sets the value of the acceptCancelledOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptCancelOfferType2 }
     *     
     */
    public void setAcceptCancelledOffer(AcceptCancelOfferType2 value) {
        this.acceptCancelledOffer = value;
    }

    /**
     * Gets the value of the acceptChange property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedOrderItemType2 }
     *     
     */
    public SelectedOrderItemType2 getAcceptChange() {
        return acceptChange;
    }

    /**
     * Sets the value of the acceptChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedOrderItemType2 }
     *     
     */
    public void setAcceptChange(SelectedOrderItemType2 value) {
        this.acceptChange = value;
    }

    /**
     * Gets the value of the acceptOrderItemList property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptOrderItemListType2 }
     *     
     */
    public AcceptOrderItemListType2 getAcceptOrderItemList() {
        return acceptOrderItemList;
    }

    /**
     * Sets the value of the acceptOrderItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptOrderItemListType2 }
     *     
     */
    public void setAcceptOrderItemList(AcceptOrderItemListType2 value) {
        this.acceptOrderItemList = value;
    }

    /**
     * Gets the value of the acceptRepricedOrder property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptRepricedOrderType2 }
     *     
     */
    public AcceptRepricedOrderType2 getAcceptRepricedOrder() {
        return acceptRepricedOrder;
    }

    /**
     * Sets the value of the acceptRepricedOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptRepricedOrderType2 }
     *     
     */
    public void setAcceptRepricedOrder(AcceptRepricedOrderType2 value) {
        this.acceptRepricedOrder = value;
    }

    /**
     * Gets the value of the acceptSelectedQuotedOfferList property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptSelectedQuotedOfferListType2 }
     *     
     */
    public AcceptSelectedQuotedOfferListType2 getAcceptSelectedQuotedOfferList() {
        return acceptSelectedQuotedOfferList;
    }

    /**
     * Sets the value of the acceptSelectedQuotedOfferList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptSelectedQuotedOfferListType2 }
     *     
     */
    public void setAcceptSelectedQuotedOfferList(AcceptSelectedQuotedOfferListType2 value) {
        this.acceptSelectedQuotedOfferList = value;
    }

    /**
     * Gets the value of the cancelUnpaidOrder property.
     * 
     * @return
     *     possible object is
     *     {@link CancelUnpaidOrderType2 }
     *     
     */
    public CancelUnpaidOrderType2 getCancelUnpaidOrder() {
        return cancelUnpaidOrder;
    }

    /**
     * Sets the value of the cancelUnpaidOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelUnpaidOrderType2 }
     *     
     */
    public void setCancelUnpaidOrder(CancelUnpaidOrderType2 value) {
        this.cancelUnpaidOrder = value;
    }

    /**
     * Gets the value of the updatePax property.
     * 
     * @return
     *     possible object is
     *     {@link OrderChangeUpdatePaxType2 }
     *     
     */
    public OrderChangeUpdatePaxType2 getUpdatePax() {
        return updatePax;
    }

    /**
     * Sets the value of the updatePax property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderChangeUpdatePaxType2 }
     *     
     */
    public void setUpdatePax(OrderChangeUpdatePaxType2 value) {
        this.updatePax = value;
    }

}
