//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * set of data, either signed or not, that delivers all that is necessary for a clearance of funds to take place when using the SwO Standard and Process. It supplies the data needed to execute the clearance using the SwO Standard and Process. It is the core data required by the Clearance Manager to process a Clearance. Optionally, it can be agreed by the Clearance Payer and the Clearance Payee of the clearance.
 * 
 * <p>Java class for ClearanceDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClearanceDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClearanceID" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearanceID_Type"/&gt;
 *         &lt;element name="ClearancePayeeData" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearancePayeeDataType"/&gt;
 *         &lt;element name="ClearancePayeeSignature" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}DigitalSignatureType" minOccurs="0"/&gt;
 *         &lt;element name="ClearancePayerData" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearancePayerDataType"/&gt;
 *         &lt;element name="ClearancePayerSignature" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}DigitalSignatureType" minOccurs="0"/&gt;
 *         &lt;element name="NetClearanceAmount" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}AmountType"/&gt;
 *         &lt;element name="PaymentCommitmentDateTime" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}DateTimeType"/&gt;
 *         &lt;element name="ProcessRuleCode" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearanceProcessRuleCodeType"/&gt;
 *         &lt;element name="RemittanceDate" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}DateType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClearanceDataType", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes", propOrder = {
    "clearanceID",
    "clearancePayeeData",
    "clearancePayeeSignature",
    "clearancePayerData",
    "clearancePayerSignature",
    "netClearanceAmount",
    "paymentCommitmentDateTime",
    "processRuleCode",
    "remittanceDate"
})
public class ClearanceDataType3 {

    @XmlElement(name = "ClearanceID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String clearanceID;
    @XmlElement(name = "ClearancePayeeData", required = true)
    protected ClearancePayeeDataType3 clearancePayeeData;
    @XmlElement(name = "ClearancePayeeSignature")
    protected PaymentDigitalSignatureType clearancePayeeSignature;
    @XmlElement(name = "ClearancePayerData", required = true)
    protected ClearancePayerDataType3 clearancePayerData;
    @XmlElement(name = "ClearancePayerSignature")
    protected PaymentDigitalSignatureType clearancePayerSignature;
    @XmlElement(name = "NetClearanceAmount", required = true)
    protected AmountType3 netClearanceAmount;
    @XmlElement(name = "PaymentCommitmentDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paymentCommitmentDateTime;
    @XmlElement(name = "ProcessRuleCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String processRuleCode;
    @XmlElement(name = "RemittanceDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar remittanceDate;

    /**
     * Gets the value of the clearanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearanceID() {
        return clearanceID;
    }

    /**
     * Sets the value of the clearanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearanceID(String value) {
        this.clearanceID = value;
    }

    /**
     * Gets the value of the clearancePayeeData property.
     * 
     * @return
     *     possible object is
     *     {@link ClearancePayeeDataType3 }
     *     
     */
    public ClearancePayeeDataType3 getClearancePayeeData() {
        return clearancePayeeData;
    }

    /**
     * Sets the value of the clearancePayeeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearancePayeeDataType3 }
     *     
     */
    public void setClearancePayeeData(ClearancePayeeDataType3 value) {
        this.clearancePayeeData = value;
    }

    /**
     * Gets the value of the clearancePayeeSignature property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDigitalSignatureType }
     *     
     */
    public PaymentDigitalSignatureType getClearancePayeeSignature() {
        return clearancePayeeSignature;
    }

    /**
     * Sets the value of the clearancePayeeSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDigitalSignatureType }
     *     
     */
    public void setClearancePayeeSignature(PaymentDigitalSignatureType value) {
        this.clearancePayeeSignature = value;
    }

    /**
     * Gets the value of the clearancePayerData property.
     * 
     * @return
     *     possible object is
     *     {@link ClearancePayerDataType3 }
     *     
     */
    public ClearancePayerDataType3 getClearancePayerData() {
        return clearancePayerData;
    }

    /**
     * Sets the value of the clearancePayerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearancePayerDataType3 }
     *     
     */
    public void setClearancePayerData(ClearancePayerDataType3 value) {
        this.clearancePayerData = value;
    }

    /**
     * Gets the value of the clearancePayerSignature property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDigitalSignatureType }
     *     
     */
    public PaymentDigitalSignatureType getClearancePayerSignature() {
        return clearancePayerSignature;
    }

    /**
     * Sets the value of the clearancePayerSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDigitalSignatureType }
     *     
     */
    public void setClearancePayerSignature(PaymentDigitalSignatureType value) {
        this.clearancePayerSignature = value;
    }

    /**
     * Gets the value of the netClearanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType3 }
     *     
     */
    public AmountType3 getNetClearanceAmount() {
        return netClearanceAmount;
    }

    /**
     * Sets the value of the netClearanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType3 }
     *     
     */
    public void setNetClearanceAmount(AmountType3 value) {
        this.netClearanceAmount = value;
    }

    /**
     * Gets the value of the paymentCommitmentDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentCommitmentDateTime() {
        return paymentCommitmentDateTime;
    }

    /**
     * Sets the value of the paymentCommitmentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentCommitmentDateTime(XMLGregorianCalendar value) {
        this.paymentCommitmentDateTime = value;
    }

    /**
     * Gets the value of the processRuleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessRuleCode() {
        return processRuleCode;
    }

    /**
     * Sets the value of the processRuleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessRuleCode(String value) {
        this.processRuleCode = value;
    }

    /**
     * Gets the value of the remittanceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRemittanceDate() {
        return remittanceDate;
    }

    /**
     * Sets the value of the remittanceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRemittanceDate(XMLGregorianCalendar value) {
        this.remittanceDate = value;
    }

}
