//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * the process that turns the promise of payment (for example, in the form of electronic clearance request) into the actual movement of money from one account to another
 * 
 * <p>Java class for ClearingProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClearingProcessType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClearanceClearingNotif" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearanceClearingNotifType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="ClearingDate" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}DateType"/&gt;
 *         &lt;element name="ClearingID" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearingID_Type"/&gt;
 *         &lt;element name="ClearingParty" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearingPartyType"/&gt;
 *         &lt;element name="FundsTransfer" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}FundsTransferType"/&gt;
 *         &lt;element name="TotalAmount" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}AmountType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClearingProcessType", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes", propOrder = {
    "clearanceClearingNotif",
    "clearingDate",
    "clearingID",
    "clearingParty",
    "fundsTransfer",
    "totalAmount"
})
public class ClearingProcessType {

    @XmlElement(name = "ClearanceClearingNotif", required = true)
    protected List<ClearanceClearingNotifType> clearanceClearingNotif;
    @XmlElement(name = "ClearingDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar clearingDate;
    @XmlElement(name = "ClearingID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String clearingID;
    @XmlElement(name = "ClearingParty", required = true)
    protected ClearingPartyType clearingParty;
    @XmlElement(name = "FundsTransfer", required = true)
    protected FundsTransferType fundsTransfer;
    @XmlElement(name = "TotalAmount", required = true)
    protected AmountType3 totalAmount;

    /**
     * Gets the value of the clearanceClearingNotif property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clearanceClearingNotif property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClearanceClearingNotif().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClearanceClearingNotifType }
     * 
     * 
     */
    public List<ClearanceClearingNotifType> getClearanceClearingNotif() {
        if (clearanceClearingNotif == null) {
            clearanceClearingNotif = new ArrayList<ClearanceClearingNotifType>();
        }
        return this.clearanceClearingNotif;
    }

    /**
     * Gets the value of the clearingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClearingDate() {
        return clearingDate;
    }

    /**
     * Sets the value of the clearingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClearingDate(XMLGregorianCalendar value) {
        this.clearingDate = value;
    }

    /**
     * Gets the value of the clearingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingID() {
        return clearingID;
    }

    /**
     * Sets the value of the clearingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingID(String value) {
        this.clearingID = value;
    }

    /**
     * Gets the value of the clearingParty property.
     * 
     * @return
     *     possible object is
     *     {@link ClearingPartyType }
     *     
     */
    public ClearingPartyType getClearingParty() {
        return clearingParty;
    }

    /**
     * Sets the value of the clearingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearingPartyType }
     *     
     */
    public void setClearingParty(ClearingPartyType value) {
        this.clearingParty = value;
    }

    /**
     * Gets the value of the fundsTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link FundsTransferType }
     *     
     */
    public FundsTransferType getFundsTransfer() {
        return fundsTransfer;
    }

    /**
     * Sets the value of the fundsTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundsTransferType }
     *     
     */
    public void setFundsTransfer(FundsTransferType value) {
        this.fundsTransfer = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType3 }
     *     
     */
    public AmountType3 getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType3 }
     *     
     */
    public void setTotalAmount(AmountType3 value) {
        this.totalAmount = value;
    }

}
