//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * the delivery of funds from one party - payer- to another party - the payee - to fulfil contractual obligations, i.e. commitment between the two parties.
 * 
 * <p>Java class for ClearanceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClearanceRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AgreementID" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ID_Type" minOccurs="0"/&gt;
 *         &lt;element name="ClearanceData" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearanceDataType"/&gt;
 *         &lt;element name="CommitmentID" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ID_Type" minOccurs="0"/&gt;
 *         &lt;element name="IATA_EasyPay" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}IATA_EasyPayType" minOccurs="0"/&gt;
 *         &lt;element name="PaymentBrandCode" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}CreditCardVendorCodeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClearanceRequestType", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes", propOrder = {
    "agreementID",
    "clearanceData",
    "commitmentID",
    "iataEasyPay",
    "paymentBrandCode"
})
public class ClearanceRequestType {

    @XmlElement(name = "AgreementID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String agreementID;
    @XmlElement(name = "ClearanceData", required = true)
    protected ClearanceDataType3 clearanceData;
    @XmlElement(name = "CommitmentID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String commitmentID;
    @XmlElement(name = "IATA_EasyPay")
    protected IATAEasyPayType2 iataEasyPay;
    @XmlElement(name = "PaymentBrandCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String paymentBrandCode;

    /**
     * Gets the value of the agreementID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementID() {
        return agreementID;
    }

    /**
     * Sets the value of the agreementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementID(String value) {
        this.agreementID = value;
    }

    /**
     * Gets the value of the clearanceData property.
     * 
     * @return
     *     possible object is
     *     {@link ClearanceDataType3 }
     *     
     */
    public ClearanceDataType3 getClearanceData() {
        return clearanceData;
    }

    /**
     * Sets the value of the clearanceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearanceDataType3 }
     *     
     */
    public void setClearanceData(ClearanceDataType3 value) {
        this.clearanceData = value;
    }

    /**
     * Gets the value of the commitmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommitmentID() {
        return commitmentID;
    }

    /**
     * Sets the value of the commitmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitmentID(String value) {
        this.commitmentID = value;
    }

    /**
     * Gets the value of the iataEasyPay property.
     * 
     * @return
     *     possible object is
     *     {@link IATAEasyPayType2 }
     *     
     */
    public IATAEasyPayType2 getIATAEasyPay() {
        return iataEasyPay;
    }

    /**
     * Sets the value of the iataEasyPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link IATAEasyPayType2 }
     *     
     */
    public void setIATAEasyPay(IATAEasyPayType2 value) {
        this.iataEasyPay = value;
    }

    /**
     * Gets the value of the paymentBrandCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentBrandCode() {
        return paymentBrandCode;
    }

    /**
     * Sets the value of the paymentBrandCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentBrandCode(String value) {
        this.paymentBrandCode = value;
    }

}
