//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConsequenceOfInactionCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConsequenceOfInactionCodeContentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Auto-acceptance"/&gt;
 *     &lt;enumeration value="Auto-cancellation"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ConsequenceOfInactionCodeContentType")
@XmlEnum
public enum ConsequenceOfInactionCodeContentType {


    /**
     * Auto-acceptance by airline
     * 
     */
    @XmlEnumValue("Auto-acceptance")
    AUTO_ACCEPTANCE("Auto-acceptance"),

    /**
     * Auto-cancellation by airline
     * 
     */
    @XmlEnumValue("Auto-cancellation")
    AUTO_CANCELLATION("Auto-cancellation");
    private final String value;

    ConsequenceOfInactionCodeContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConsequenceOfInactionCodeContentType fromValue(String v) {
        for (ConsequenceOfInactionCodeContentType c: ConsequenceOfInactionCodeContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
