//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Create Order
 * 
 * <p>Java class for CreateOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateOrderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="AcceptOrderItemList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}AcceptOrderItemListType"/&gt;
 *         &lt;element name="AcceptSelectedQuotedOfferList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}AcceptSelectedQuotedOfferListType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateOrderType", propOrder = {
    "acceptOrderItemList",
    "acceptSelectedQuotedOfferList"
})
public class CreateOrderType {

    @XmlElement(name = "AcceptOrderItemList")
    protected AcceptOrderItemListType acceptOrderItemList;
    @XmlElement(name = "AcceptSelectedQuotedOfferList")
    protected AcceptSelectedQuotedOfferListType acceptSelectedQuotedOfferList;

    /**
     * Gets the value of the acceptOrderItemList property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptOrderItemListType }
     *     
     */
    public AcceptOrderItemListType getAcceptOrderItemList() {
        return acceptOrderItemList;
    }

    /**
     * Sets the value of the acceptOrderItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptOrderItemListType }
     *     
     */
    public void setAcceptOrderItemList(AcceptOrderItemListType value) {
        this.acceptOrderItemList = value;
    }

    /**
     * Gets the value of the acceptSelectedQuotedOfferList property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptSelectedQuotedOfferListType }
     *     
     */
    public AcceptSelectedQuotedOfferListType getAcceptSelectedQuotedOfferList() {
        return acceptSelectedQuotedOfferList;
    }

    /**
     * Sets the value of the acceptSelectedQuotedOfferList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptSelectedQuotedOfferListType }
     *     
     */
    public void setAcceptSelectedQuotedOfferList(AcceptSelectedQuotedOfferListType value) {
        this.acceptSelectedQuotedOfferList = value;
    }

}
