//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;


/**
 * The nonstop operation of a transport vehicle between the departure station and the arrival station. Can be used for aircrafts as well as other transport vehicles such as train or bus etc.
 * 
 * <p>Java class for DatedOperatingLegType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatedOperatingLegType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AirlineTaxonomy" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AirlineTaxonomyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Arrival" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}TransportPointType" minOccurs="0"/&gt;
 *         &lt;element name="CarrierAircraftType" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CarrierAircraftTypeType" minOccurs="0"/&gt;
 *         &lt;element name="ChangeofGaugeInd" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}IndType" minOccurs="0"/&gt;
 *         &lt;element name="DatedOperatingLegID" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ID_Type" minOccurs="0"/&gt;
 *         &lt;element name="Dep" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}TransportPointType" minOccurs="0"/&gt;
 *         &lt;element name="DistanceMeasure" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}MeasureType" minOccurs="0"/&gt;
 *         &lt;element name="IATA_AircraftType" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}IATA_AircraftTypeType" minOccurs="0"/&gt;
 *         &lt;element name="OnGroundDuration" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DurationType" minOccurs="0"/&gt;
 *         &lt;element name="RichMedia" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}MediaResourceRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatedOperatingLegType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "airlineTaxonomy",
    "arrival",
    "carrierAircraftType",
    "changeofGaugeInd",
    "datedOperatingLegID",
    "dep",
    "distanceMeasure",
    "iataAircraftType",
    "onGroundDuration",
    "richMedia"
})
public class DatedOperatingLegType2 {

    @XmlElement(name = "AirlineTaxonomy")
    protected List<AirlineTaxonomyType2> airlineTaxonomy;
    @XmlElement(name = "Arrival")
    protected TransportPointType2 arrival;
    @XmlElement(name = "CarrierAircraftType")
    protected CarrierAircraftTypeType2 carrierAircraftType;
    @XmlElement(name = "ChangeofGaugeInd")
    protected Boolean changeofGaugeInd;
    @XmlElement(name = "DatedOperatingLegID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String datedOperatingLegID;
    @XmlElement(name = "Dep")
    protected TransportPointType2 dep;
    @XmlElement(name = "DistanceMeasure")
    protected MeasureType2 distanceMeasure;
    @XmlElement(name = "IATA_AircraftType")
    protected IATAAircraftTypeType2 iataAircraftType;
    @XmlElement(name = "OnGroundDuration")
    protected Duration onGroundDuration;
    @XmlElement(name = "RichMedia")
    protected List<MediaResourceRefType2> richMedia;

    /**
     * Gets the value of the airlineTaxonomy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the airlineTaxonomy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAirlineTaxonomy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirlineTaxonomyType2 }
     * 
     * 
     */
    public List<AirlineTaxonomyType2> getAirlineTaxonomy() {
        if (airlineTaxonomy == null) {
            airlineTaxonomy = new ArrayList<AirlineTaxonomyType2>();
        }
        return this.airlineTaxonomy;
    }

    /**
     * Gets the value of the arrival property.
     * 
     * @return
     *     possible object is
     *     {@link TransportPointType2 }
     *     
     */
    public TransportPointType2 getArrival() {
        return arrival;
    }

    /**
     * Sets the value of the arrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportPointType2 }
     *     
     */
    public void setArrival(TransportPointType2 value) {
        this.arrival = value;
    }

    /**
     * Gets the value of the carrierAircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierAircraftTypeType2 }
     *     
     */
    public CarrierAircraftTypeType2 getCarrierAircraftType() {
        return carrierAircraftType;
    }

    /**
     * Sets the value of the carrierAircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierAircraftTypeType2 }
     *     
     */
    public void setCarrierAircraftType(CarrierAircraftTypeType2 value) {
        this.carrierAircraftType = value;
    }

    /**
     * Gets the value of the changeofGaugeInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangeofGaugeInd() {
        return changeofGaugeInd;
    }

    /**
     * Sets the value of the changeofGaugeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeofGaugeInd(Boolean value) {
        this.changeofGaugeInd = value;
    }

    /**
     * Gets the value of the datedOperatingLegID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatedOperatingLegID() {
        return datedOperatingLegID;
    }

    /**
     * Sets the value of the datedOperatingLegID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatedOperatingLegID(String value) {
        this.datedOperatingLegID = value;
    }

    /**
     * Gets the value of the dep property.
     * 
     * @return
     *     possible object is
     *     {@link TransportPointType2 }
     *     
     */
    public TransportPointType2 getDep() {
        return dep;
    }

    /**
     * Sets the value of the dep property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportPointType2 }
     *     
     */
    public void setDep(TransportPointType2 value) {
        this.dep = value;
    }

    /**
     * Gets the value of the distanceMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType2 }
     *     
     */
    public MeasureType2 getDistanceMeasure() {
        return distanceMeasure;
    }

    /**
     * Sets the value of the distanceMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType2 }
     *     
     */
    public void setDistanceMeasure(MeasureType2 value) {
        this.distanceMeasure = value;
    }

    /**
     * Gets the value of the iataAircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link IATAAircraftTypeType2 }
     *     
     */
    public IATAAircraftTypeType2 getIATAAircraftType() {
        return iataAircraftType;
    }

    /**
     * Sets the value of the iataAircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IATAAircraftTypeType2 }
     *     
     */
    public void setIATAAircraftType(IATAAircraftTypeType2 value) {
        this.iataAircraftType = value;
    }

    /**
     * Gets the value of the onGroundDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getOnGroundDuration() {
        return onGroundDuration;
    }

    /**
     * Sets the value of the onGroundDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setOnGroundDuration(Duration value) {
        this.onGroundDuration = value;
    }

    /**
     * Gets the value of the richMedia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the richMedia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRichMedia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MediaResourceRefType2 }
     * 
     * 
     */
    public List<MediaResourceRefType2> getRichMedia() {
        if (richMedia == null) {
            richMedia = new ArrayList<MediaResourceRefType2>();
        }
        return this.richMedia;
    }

}
