//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Payment Card details passed onto airline in an encrypted format.
 * 
 * <p>Java class for EncryptedDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptedDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CryptographyKey" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}CryptographyKeyType"/&gt;
 *         &lt;element name="CypherData" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}CypherDataType"/&gt;
 *         &lt;element name="EncryptedCardNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}BinaryObjectType"/&gt;
 *         &lt;element name="EncryptedCardSecurityNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}BinaryObjectType"/&gt;
 *         &lt;element name="First6DigitsText" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}First6DigitsTextType"/&gt;
 *         &lt;element name="KeyNameText" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}TextType"/&gt;
 *         &lt;element name="Last4DigitsText" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}Last4DigitsTextType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptedDataType", propOrder = {
    "cryptographyKey",
    "cypherData",
    "encryptedCardNumber",
    "encryptedCardSecurityNumber",
    "first6DigitsText",
    "keyNameText",
    "last4DigitsText"
})
public class EncryptedDataType {

    @XmlElement(name = "CryptographyKey", required = true)
    protected CryptographyKeyType cryptographyKey;
    @XmlElement(name = "CypherData", required = true)
    protected CypherDataType cypherData;
    @XmlElement(name = "EncryptedCardNumber", required = true)
    protected BinaryObjectType encryptedCardNumber;
    @XmlElement(name = "EncryptedCardSecurityNumber", required = true)
    protected BinaryObjectType encryptedCardSecurityNumber;
    @XmlElement(name = "First6DigitsText", required = true)
    protected String first6DigitsText;
    @XmlElement(name = "KeyNameText", required = true)
    protected String keyNameText;
    @XmlElement(name = "Last4DigitsText", required = true)
    protected String last4DigitsText;

    /**
     * Gets the value of the cryptographyKey property.
     * 
     * @return
     *     possible object is
     *     {@link CryptographyKeyType }
     *     
     */
    public CryptographyKeyType getCryptographyKey() {
        return cryptographyKey;
    }

    /**
     * Sets the value of the cryptographyKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CryptographyKeyType }
     *     
     */
    public void setCryptographyKey(CryptographyKeyType value) {
        this.cryptographyKey = value;
    }

    /**
     * Gets the value of the cypherData property.
     * 
     * @return
     *     possible object is
     *     {@link CypherDataType }
     *     
     */
    public CypherDataType getCypherData() {
        return cypherData;
    }

    /**
     * Sets the value of the cypherData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CypherDataType }
     *     
     */
    public void setCypherData(CypherDataType value) {
        this.cypherData = value;
    }

    /**
     * Gets the value of the encryptedCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryObjectType }
     *     
     */
    public BinaryObjectType getEncryptedCardNumber() {
        return encryptedCardNumber;
    }

    /**
     * Sets the value of the encryptedCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryObjectType }
     *     
     */
    public void setEncryptedCardNumber(BinaryObjectType value) {
        this.encryptedCardNumber = value;
    }

    /**
     * Gets the value of the encryptedCardSecurityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryObjectType }
     *     
     */
    public BinaryObjectType getEncryptedCardSecurityNumber() {
        return encryptedCardSecurityNumber;
    }

    /**
     * Sets the value of the encryptedCardSecurityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryObjectType }
     *     
     */
    public void setEncryptedCardSecurityNumber(BinaryObjectType value) {
        this.encryptedCardSecurityNumber = value;
    }

    /**
     * Gets the value of the first6DigitsText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirst6DigitsText() {
        return first6DigitsText;
    }

    /**
     * Sets the value of the first6DigitsText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirst6DigitsText(String value) {
        this.first6DigitsText = value;
    }

    /**
     * Gets the value of the keyNameText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyNameText() {
        return keyNameText;
    }

    /**
     * Sets the value of the keyNameText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyNameText(String value) {
        this.keyNameText = value;
    }

    /**
     * Gets the value of the last4DigitsText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLast4DigitsText() {
        return last4DigitsText;
    }

    /**
     * Sets the value of the last4DigitsText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLast4DigitsText(String value) {
        this.last4DigitsText = value;
    }

}
