//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Excess baggage information displayed on a coupon.
 * 
 * <p>Java class for ExcessBaggageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExcessBaggageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Amount" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="ExcessBaggageMeasure" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}MeasureType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExcessBaggageType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "amount",
    "excessBaggageMeasure"
})
public class ExcessBaggageType2 {

    @XmlElement(name = "Amount")
    protected AmountType2 amount;
    @XmlElement(name = "ExcessBaggageMeasure")
    protected MeasureType2 excessBaggageMeasure;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType2 }
     *     
     */
    public AmountType2 getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType2 }
     *     
     */
    public void setAmount(AmountType2 value) {
        this.amount = value;
    }

    /**
     * Gets the value of the excessBaggageMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType2 }
     *     
     */
    public MeasureType2 getExcessBaggageMeasure() {
        return excessBaggageMeasure;
    }

    /**
     * Sets the value of the excessBaggageMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType2 }
     *     
     */
    public void setExcessBaggageMeasure(MeasureType2 value) {
        this.excessBaggageMeasure = value;
    }

}
