//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Filed fee information relating to a coupon, including the Bankers Seller Rate used to convert the filed amount into the currency of payment.
 * 
 * <p>Java class for FiledFeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiledFeeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BankersSellerRate" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}RateType" minOccurs="0"/&gt;
 *         &lt;element name="FeeAmount" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AmountType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiledFeeType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "bankersSellerRate",
    "feeAmount"
})
public class FiledFeeType2 {

    @XmlElement(name = "BankersSellerRate")
    protected RateType2 bankersSellerRate;
    @XmlElement(name = "FeeAmount")
    protected AmountType2 feeAmount;

    /**
     * Gets the value of the bankersSellerRate property.
     * 
     * @return
     *     possible object is
     *     {@link RateType2 }
     *     
     */
    public RateType2 getBankersSellerRate() {
        return bankersSellerRate;
    }

    /**
     * Sets the value of the bankersSellerRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateType2 }
     *     
     */
    public void setBankersSellerRate(RateType2 value) {
        this.bankersSellerRate = value;
    }

    /**
     * Gets the value of the feeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType2 }
     *     
     */
    public AmountType2 getFeeAmount() {
        return feeAmount;
    }

    /**
     * Sets the value of the feeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType2 }
     *     
     */
    public void setFeeAmount(AmountType2 value) {
        this.feeAmount = value;
    }

}
