//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Flight filter criteria including aircraft features, Cabin Type, RBD, and Tail Number.
 * 
 * <p>Java class for FlightCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightCriteriaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FlightCharacteristicsCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}FlightCharacteristicsCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="IATA_AircraftType" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}IATA_AircraftTypeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="RBD" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}RBD_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightCriteriaType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "flightCharacteristicsCriteria",
    "iataAircraftType",
    "rbd"
})
public class FlightCriteriaType2 {

    @XmlElement(name = "FlightCharacteristicsCriteria")
    protected List<FlightCharacteristicsCriteriaType2> flightCharacteristicsCriteria;
    @XmlElement(name = "IATA_AircraftType")
    protected List<IATAAircraftTypeType2> iataAircraftType;
    @XmlElement(name = "RBD")
    protected List<RBDType2> rbd;

    /**
     * Gets the value of the flightCharacteristicsCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightCharacteristicsCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightCharacteristicsCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightCharacteristicsCriteriaType2 }
     * 
     * 
     */
    public List<FlightCharacteristicsCriteriaType2> getFlightCharacteristicsCriteria() {
        if (flightCharacteristicsCriteria == null) {
            flightCharacteristicsCriteria = new ArrayList<FlightCharacteristicsCriteriaType2>();
        }
        return this.flightCharacteristicsCriteria;
    }

    /**
     * Gets the value of the iataAircraftType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iataAircraftType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIATAAircraftType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IATAAircraftTypeType2 }
     * 
     * 
     */
    public List<IATAAircraftTypeType2> getIATAAircraftType() {
        if (iataAircraftType == null) {
            iataAircraftType = new ArrayList<IATAAircraftTypeType2>();
        }
        return this.iataAircraftType;
    }

    /**
     * Gets the value of the rbd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rbd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRBD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RBDType2 }
     * 
     * 
     */
    public List<RBDType2> getRBD() {
        if (rbd == null) {
            rbd = new ArrayList<RBDType2>();
        }
        return this.rbd;
    }

}
