//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Further qualifies the flight request by influencing which results are returned in the shopping response, including preferred or required criteria.
 * 
 * <p>Java class for FlightRelatedCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightRelatedCriteriaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AllianceCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AllianceCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CarrierCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CarrierCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ConnectionCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ConnectionCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="FlightCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}FlightCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="OfferItemTypeCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}OfferItemTypeCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SegmentDurationCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}SegmentDurationCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TripPurposeCode" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}TripPurposeCodeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightRelatedCriteriaType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "allianceCriteria",
    "carrierCriteria",
    "connectionCriteria",
    "flightCriteria",
    "offerItemTypeCriteria",
    "segmentDurationCriteria",
    "tripPurposeCode"
})
public class FlightRelatedCriteriaType2 {

    @XmlElement(name = "AllianceCriteria")
    protected List<AllianceCriteriaType2> allianceCriteria;
    @XmlElement(name = "CarrierCriteria")
    protected List<CarrierCriteriaType2> carrierCriteria;
    @XmlElement(name = "ConnectionCriteria")
    protected List<ConnectionCriteriaType2> connectionCriteria;
    @XmlElement(name = "FlightCriteria")
    protected List<FlightCriteriaType2> flightCriteria;
    @XmlElement(name = "OfferItemTypeCriteria")
    protected List<OfferItemTypeCriteriaType2> offerItemTypeCriteria;
    @XmlElement(name = "SegmentDurationCriteria")
    protected List<SegmentDurationCriteriaType2> segmentDurationCriteria;
    @XmlElement(name = "TripPurposeCode")
    @XmlSchemaType(name = "string")
    protected TripPurposeCodeContentType2 tripPurposeCode;

    /**
     * Gets the value of the allianceCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allianceCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllianceCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllianceCriteriaType2 }
     * 
     * 
     */
    public List<AllianceCriteriaType2> getAllianceCriteria() {
        if (allianceCriteria == null) {
            allianceCriteria = new ArrayList<AllianceCriteriaType2>();
        }
        return this.allianceCriteria;
    }

    /**
     * Gets the value of the carrierCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the carrierCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCarrierCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CarrierCriteriaType2 }
     * 
     * 
     */
    public List<CarrierCriteriaType2> getCarrierCriteria() {
        if (carrierCriteria == null) {
            carrierCriteria = new ArrayList<CarrierCriteriaType2>();
        }
        return this.carrierCriteria;
    }

    /**
     * Gets the value of the connectionCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectionCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConnectionCriteriaType2 }
     * 
     * 
     */
    public List<ConnectionCriteriaType2> getConnectionCriteria() {
        if (connectionCriteria == null) {
            connectionCriteria = new ArrayList<ConnectionCriteriaType2>();
        }
        return this.connectionCriteria;
    }

    /**
     * Gets the value of the flightCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightCriteriaType2 }
     * 
     * 
     */
    public List<FlightCriteriaType2> getFlightCriteria() {
        if (flightCriteria == null) {
            flightCriteria = new ArrayList<FlightCriteriaType2>();
        }
        return this.flightCriteria;
    }

    /**
     * Gets the value of the offerItemTypeCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerItemTypeCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferItemTypeCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfferItemTypeCriteriaType2 }
     * 
     * 
     */
    public List<OfferItemTypeCriteriaType2> getOfferItemTypeCriteria() {
        if (offerItemTypeCriteria == null) {
            offerItemTypeCriteria = new ArrayList<OfferItemTypeCriteriaType2>();
        }
        return this.offerItemTypeCriteria;
    }

    /**
     * Gets the value of the segmentDurationCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentDurationCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentDurationCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentDurationCriteriaType2 }
     * 
     * 
     */
    public List<SegmentDurationCriteriaType2> getSegmentDurationCriteria() {
        if (segmentDurationCriteria == null) {
            segmentDurationCriteria = new ArrayList<SegmentDurationCriteriaType2>();
        }
        return this.segmentDurationCriteria;
    }

    /**
     * Gets the value of the tripPurposeCode property.
     * 
     * @return
     *     possible object is
     *     {@link TripPurposeCodeContentType2 }
     *     
     */
    public TripPurposeCodeContentType2 getTripPurposeCode() {
        return tripPurposeCode;
    }

    /**
     * Sets the value of the tripPurposeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TripPurposeCodeContentType2 }
     *     
     */
    public void setTripPurposeCode(TripPurposeCodeContentType2 value) {
        this.tripPurposeCode = value;
    }

}
