//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A location with a spatial attribute, probably on the surface of the earth. For example: Longitude and Latitude
 * 
 * <p>Java class for GeospatialLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeospatialLocationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NaturalAreaGeocode" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="PointElevationNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}NumberType" minOccurs="0"/&gt;
 *         &lt;element name="PointLatitudeNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}NumberType" minOccurs="0"/&gt;
 *         &lt;element name="PointLongitudeNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}NumberType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeospatialLocationType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "naturalAreaGeocode",
    "pointElevationNumber",
    "pointLatitudeNumber",
    "pointLongitudeNumber"
})
public class GeospatialLocationType2 {

    @XmlElement(name = "NaturalAreaGeocode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String naturalAreaGeocode;
    @XmlElement(name = "PointElevationNumber")
    protected BigDecimal pointElevationNumber;
    @XmlElement(name = "PointLatitudeNumber")
    protected BigDecimal pointLatitudeNumber;
    @XmlElement(name = "PointLongitudeNumber")
    protected BigDecimal pointLongitudeNumber;

    /**
     * Gets the value of the naturalAreaGeocode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaturalAreaGeocode() {
        return naturalAreaGeocode;
    }

    /**
     * Sets the value of the naturalAreaGeocode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaturalAreaGeocode(String value) {
        this.naturalAreaGeocode = value;
    }

    /**
     * Gets the value of the pointElevationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPointElevationNumber() {
        return pointElevationNumber;
    }

    /**
     * Sets the value of the pointElevationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPointElevationNumber(BigDecimal value) {
        this.pointElevationNumber = value;
    }

    /**
     * Gets the value of the pointLatitudeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPointLatitudeNumber() {
        return pointLatitudeNumber;
    }

    /**
     * Sets the value of the pointLatitudeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPointLatitudeNumber(BigDecimal value) {
        this.pointLatitudeNumber = value;
    }

    /**
     * Gets the value of the pointLongitudeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPointLongitudeNumber() {
        return pointLongitudeNumber;
    }

    /**
     * Sets the value of the pointLongitudeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPointLongitudeNumber(BigDecimal value) {
        this.pointLongitudeNumber = value;
    }

}
