//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ClearanceFilterCriteria" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearanceFilterCriteriaType" maxOccurs="unbounded"/&gt;
 *           &lt;element name="ClearanceID" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}ClearanceID_Type" maxOccurs="unbounded"/&gt;
 *           &lt;element name="OtherID" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}OtherID_Type" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="PayloadStandardAttributes" type="{http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceCommonTypes}IATA_PayloadStandardAttributesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clearanceFilterCriteria",
    "clearanceID",
    "otherID",
    "payloadStandardAttributes"
})
@XmlRootElement(name = "IATA_PaymentClearanceListRQ", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceListRQ")
public class IATAPaymentClearanceListRQ {

    @XmlElement(name = "ClearanceFilterCriteria", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceListRQ")
    protected List<ClearanceFilterCriteriaType> clearanceFilterCriteria;
    @XmlElement(name = "ClearanceID", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceListRQ")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> clearanceID;
    @XmlElement(name = "OtherID", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceListRQ")
    protected List<OtherIDType> otherID;
    @XmlElement(name = "PayloadStandardAttributes", namespace = "http://www.iata.org/IATA/2015/00/2022.1/IATA_PaymentClearanceListRQ")
    protected IATAPayloadStandardAttributesType3 payloadStandardAttributes;

    /**
     * Gets the value of the clearanceFilterCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clearanceFilterCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClearanceFilterCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClearanceFilterCriteriaType }
     * 
     * 
     */
    public List<ClearanceFilterCriteriaType> getClearanceFilterCriteria() {
        if (clearanceFilterCriteria == null) {
            clearanceFilterCriteria = new ArrayList<ClearanceFilterCriteriaType>();
        }
        return this.clearanceFilterCriteria;
    }

    /**
     * Gets the value of the clearanceID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clearanceID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClearanceID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getClearanceID() {
        if (clearanceID == null) {
            clearanceID = new ArrayList<String>();
        }
        return this.clearanceID;
    }

    /**
     * Gets the value of the otherID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherIDType }
     * 
     * 
     */
    public List<OtherIDType> getOtherID() {
        if (otherID == null) {
            otherID = new ArrayList<OtherIDType>();
        }
        return this.otherID;
    }

    /**
     * Gets the value of the payloadStandardAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link IATAPayloadStandardAttributesType3 }
     *     
     */
    public IATAPayloadStandardAttributesType3 getPayloadStandardAttributes() {
        return payloadStandardAttributes;
    }

    /**
     * Sets the value of the payloadStandardAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link IATAPayloadStandardAttributesType3 }
     *     
     */
    public void setPayloadStandardAttributes(IATAPayloadStandardAttributesType3 value) {
        this.payloadStandardAttributes = value;
    }

}
