//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Order Service Association
 * 
 * <p>Java class for OrderServiceAssociationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderServiceAssociationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="PaxSegmentRef" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}PaxSegmentRefType"/&gt;
 *         &lt;element name="SeatOnLeg" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}SeatOnLegType"/&gt;
 *         &lt;element name="ServiceDefinitionRef" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}OrderServiceDefinitionRefType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderServiceAssociationType", propOrder = {
    "paxSegmentRef",
    "seatOnLeg",
    "serviceDefinitionRef"
})
public class OrderServiceAssociationType {

    @XmlElement(name = "PaxSegmentRef")
    protected PaxSegmentRefType paxSegmentRef;
    @XmlElement(name = "SeatOnLeg")
    protected SeatOnLegType seatOnLeg;
    @XmlElement(name = "ServiceDefinitionRef")
    protected OrderServiceDefinitionRefType serviceDefinitionRef;

    /**
     * Gets the value of the paxSegmentRef property.
     * 
     * @return
     *     possible object is
     *     {@link PaxSegmentRefType }
     *     
     */
    public PaxSegmentRefType getPaxSegmentRef() {
        return paxSegmentRef;
    }

    /**
     * Sets the value of the paxSegmentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaxSegmentRefType }
     *     
     */
    public void setPaxSegmentRef(PaxSegmentRefType value) {
        this.paxSegmentRef = value;
    }

    /**
     * Gets the value of the seatOnLeg property.
     * 
     * @return
     *     possible object is
     *     {@link SeatOnLegType }
     *     
     */
    public SeatOnLegType getSeatOnLeg() {
        return seatOnLeg;
    }

    /**
     * Sets the value of the seatOnLeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeatOnLegType }
     *     
     */
    public void setSeatOnLeg(SeatOnLegType value) {
        this.seatOnLeg = value;
    }

    /**
     * Gets the value of the serviceDefinitionRef property.
     * 
     * @return
     *     possible object is
     *     {@link OrderServiceDefinitionRefType }
     *     
     */
    public OrderServiceDefinitionRefType getServiceDefinitionRef() {
        return serviceDefinitionRef;
    }

    /**
     * Sets the value of the serviceDefinitionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderServiceDefinitionRefType }
     *     
     */
    public void setServiceDefinitionRef(OrderServiceDefinitionRefType value) {
        this.serviceDefinitionRef = value;
    }

}
