//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Request content for Order Reshop message
 * 
 * <p>Java class for OrderReshopRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderReshopRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BookingRef" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}BookingRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ContactInfoList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ContactInfoListType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DatedMarketingSegmentList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DatedMarketingSegmentListType" minOccurs="0"/&gt;
 *         &lt;element name="DatedOperatingLegList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DatedOperatingLegListType" minOccurs="0"/&gt;
 *         &lt;element name="DatedOperatingSegmentList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DatedOperatingSegmentListType" minOccurs="0"/&gt;
 *         &lt;element name="DisclosureList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DisclosureListType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="FareWaiver" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}FareWaiverType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="OrderRefID" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ID_Type" minOccurs="0"/&gt;
 *         &lt;element name="OrderVersionNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}OrderVersionNumberType" minOccurs="0"/&gt;
 *         &lt;element name="PaxJourneyList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ShoppingRequestPaxJourneyListType" minOccurs="0"/&gt;
 *         &lt;element name="PayloadRestrictions" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PayloadRestrictionsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PaymentFunctions" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PaymentAssociatedFunctionsCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ResponseParameters" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ResponseParametersRequestType" minOccurs="0"/&gt;
 *         &lt;element name="UpdateOrder" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}UpdateOrderType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderReshopRequestType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "bookingRef",
    "contactInfoList",
    "datedMarketingSegmentList",
    "datedOperatingLegList",
    "datedOperatingSegmentList",
    "disclosureList",
    "fareWaiver",
    "orderRefID",
    "orderVersionNumber",
    "paxJourneyList",
    "payloadRestrictions",
    "paymentFunctions",
    "responseParameters",
    "updateOrder"
})
public class OrderReshopRequestType2 {

    @XmlElement(name = "BookingRef")
    protected List<BookingRefType2> bookingRef;
    @XmlElement(name = "ContactInfoList")
    protected List<ContactInfoListType2> contactInfoList;
    @XmlElement(name = "DatedMarketingSegmentList")
    protected DatedMarketingSegmentListType2 datedMarketingSegmentList;
    @XmlElement(name = "DatedOperatingLegList")
    protected DatedOperatingLegListType2 datedOperatingLegList;
    @XmlElement(name = "DatedOperatingSegmentList")
    protected DatedOperatingSegmentListType2 datedOperatingSegmentList;
    @XmlElement(name = "DisclosureList")
    protected List<DisclosureListType2> disclosureList;
    @XmlElement(name = "FareWaiver")
    protected List<FareWaiverType2> fareWaiver;
    @XmlElement(name = "OrderRefID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String orderRefID;
    @XmlElement(name = "OrderVersionNumber")
    protected BigInteger orderVersionNumber;
    @XmlElement(name = "PaxJourneyList")
    protected ShoppingRequestPaxJourneyListType2 paxJourneyList;
    @XmlElement(name = "PayloadRestrictions")
    protected List<PayloadRestrictionsType2> payloadRestrictions;
    @XmlElement(name = "PaymentFunctions")
    protected List<PaymentAssociatedFunctionsCriteriaType2> paymentFunctions;
    @XmlElement(name = "ResponseParameters")
    protected ResponseParametersRequestType2 responseParameters;
    @XmlElement(name = "UpdateOrder")
    protected UpdateOrderType2 updateOrder;

    /**
     * Gets the value of the bookingRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bookingRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBookingRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BookingRefType2 }
     * 
     * 
     */
    public List<BookingRefType2> getBookingRef() {
        if (bookingRef == null) {
            bookingRef = new ArrayList<BookingRefType2>();
        }
        return this.bookingRef;
    }

    /**
     * Gets the value of the contactInfoList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactInfoList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactInfoList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInfoListType2 }
     * 
     * 
     */
    public List<ContactInfoListType2> getContactInfoList() {
        if (contactInfoList == null) {
            contactInfoList = new ArrayList<ContactInfoListType2>();
        }
        return this.contactInfoList;
    }

    /**
     * Gets the value of the datedMarketingSegmentList property.
     * 
     * @return
     *     possible object is
     *     {@link DatedMarketingSegmentListType2 }
     *     
     */
    public DatedMarketingSegmentListType2 getDatedMarketingSegmentList() {
        return datedMarketingSegmentList;
    }

    /**
     * Sets the value of the datedMarketingSegmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatedMarketingSegmentListType2 }
     *     
     */
    public void setDatedMarketingSegmentList(DatedMarketingSegmentListType2 value) {
        this.datedMarketingSegmentList = value;
    }

    /**
     * Gets the value of the datedOperatingLegList property.
     * 
     * @return
     *     possible object is
     *     {@link DatedOperatingLegListType2 }
     *     
     */
    public DatedOperatingLegListType2 getDatedOperatingLegList() {
        return datedOperatingLegList;
    }

    /**
     * Sets the value of the datedOperatingLegList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatedOperatingLegListType2 }
     *     
     */
    public void setDatedOperatingLegList(DatedOperatingLegListType2 value) {
        this.datedOperatingLegList = value;
    }

    /**
     * Gets the value of the datedOperatingSegmentList property.
     * 
     * @return
     *     possible object is
     *     {@link DatedOperatingSegmentListType2 }
     *     
     */
    public DatedOperatingSegmentListType2 getDatedOperatingSegmentList() {
        return datedOperatingSegmentList;
    }

    /**
     * Sets the value of the datedOperatingSegmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatedOperatingSegmentListType2 }
     *     
     */
    public void setDatedOperatingSegmentList(DatedOperatingSegmentListType2 value) {
        this.datedOperatingSegmentList = value;
    }

    /**
     * Gets the value of the disclosureList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disclosureList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisclosureList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisclosureListType2 }
     * 
     * 
     */
    public List<DisclosureListType2> getDisclosureList() {
        if (disclosureList == null) {
            disclosureList = new ArrayList<DisclosureListType2>();
        }
        return this.disclosureList;
    }

    /**
     * Gets the value of the fareWaiver property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fareWaiver property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFareWaiver().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FareWaiverType2 }
     * 
     * 
     */
    public List<FareWaiverType2> getFareWaiver() {
        if (fareWaiver == null) {
            fareWaiver = new ArrayList<FareWaiverType2>();
        }
        return this.fareWaiver;
    }

    /**
     * Gets the value of the orderRefID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderRefID() {
        return orderRefID;
    }

    /**
     * Sets the value of the orderRefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderRefID(String value) {
        this.orderRefID = value;
    }

    /**
     * Gets the value of the orderVersionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderVersionNumber() {
        return orderVersionNumber;
    }

    /**
     * Sets the value of the orderVersionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderVersionNumber(BigInteger value) {
        this.orderVersionNumber = value;
    }

    /**
     * Gets the value of the paxJourneyList property.
     * 
     * @return
     *     possible object is
     *     {@link ShoppingRequestPaxJourneyListType2 }
     *     
     */
    public ShoppingRequestPaxJourneyListType2 getPaxJourneyList() {
        return paxJourneyList;
    }

    /**
     * Sets the value of the paxJourneyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShoppingRequestPaxJourneyListType2 }
     *     
     */
    public void setPaxJourneyList(ShoppingRequestPaxJourneyListType2 value) {
        this.paxJourneyList = value;
    }

    /**
     * Gets the value of the payloadRestrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payloadRestrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayloadRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayloadRestrictionsType2 }
     * 
     * 
     */
    public List<PayloadRestrictionsType2> getPayloadRestrictions() {
        if (payloadRestrictions == null) {
            payloadRestrictions = new ArrayList<PayloadRestrictionsType2>();
        }
        return this.payloadRestrictions;
    }

    /**
     * Gets the value of the paymentFunctions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentFunctions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentFunctions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentAssociatedFunctionsCriteriaType2 }
     * 
     * 
     */
    public List<PaymentAssociatedFunctionsCriteriaType2> getPaymentFunctions() {
        if (paymentFunctions == null) {
            paymentFunctions = new ArrayList<PaymentAssociatedFunctionsCriteriaType2>();
        }
        return this.paymentFunctions;
    }

    /**
     * Gets the value of the responseParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseParametersRequestType2 }
     *     
     */
    public ResponseParametersRequestType2 getResponseParameters() {
        return responseParameters;
    }

    /**
     * Sets the value of the responseParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseParametersRequestType2 }
     *     
     */
    public void setResponseParameters(ResponseParametersRequestType2 value) {
        this.responseParameters = value;
    }

    /**
     * Gets the value of the updateOrder property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateOrderType2 }
     *     
     */
    public UpdateOrderType2 getUpdateOrder() {
        return updateOrder;
    }

    /**
     * Sets the value of the updateOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateOrderType2 }
     *     
     */
    public void setUpdateOrder(UpdateOrderType2 value) {
        this.updateOrder = value;
    }

}
