//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Physical container for message data elements
 * 
 * <p>Java class for OrderQuotePayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderQuotePayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ContactInfoList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ContactInfoListType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ExistingOrder" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ExistingOrderType" minOccurs="0"/&gt;
 *         &lt;element name="FareWaiver" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}FareWaiverType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="OrderCriteria" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}OrderCriteriaType" minOccurs="0"/&gt;
 *         &lt;element name="PaxList" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PaxType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PaymentFunctions" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PaymentAssociatedFunctionsCriteriaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="RepricedOrder" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}RepricedOrderType" minOccurs="0"/&gt;
 *         &lt;element name="ResponseParameters" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ResponseParametersRequestType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SelectedOffers" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}SelectedOfferType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderQuotePayloadType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "contactInfoList",
    "existingOrder",
    "fareWaiver",
    "orderCriteria",
    "paxList",
    "paymentFunctions",
    "repricedOrder",
    "responseParameters",
    "selectedOffers"
})
public class OrderQuotePayloadType2 {

    @XmlElement(name = "ContactInfoList")
    protected List<ContactInfoListType2> contactInfoList;
    @XmlElement(name = "ExistingOrder")
    protected ExistingOrderType2 existingOrder;
    @XmlElement(name = "FareWaiver")
    protected List<FareWaiverType2> fareWaiver;
    @XmlElement(name = "OrderCriteria")
    protected OrderCriteriaType2 orderCriteria;
    @XmlElement(name = "PaxList")
    protected List<PaxType2> paxList;
    @XmlElement(name = "PaymentFunctions")
    protected List<PaymentAssociatedFunctionsCriteriaType2> paymentFunctions;
    @XmlElement(name = "RepricedOrder")
    protected RepricedOrderType2 repricedOrder;
    @XmlElement(name = "ResponseParameters")
    protected List<ResponseParametersRequestType2> responseParameters;
    @XmlElement(name = "SelectedOffers")
    protected List<SelectedOfferType2> selectedOffers;

    /**
     * Gets the value of the contactInfoList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactInfoList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactInfoList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInfoListType2 }
     * 
     * 
     */
    public List<ContactInfoListType2> getContactInfoList() {
        if (contactInfoList == null) {
            contactInfoList = new ArrayList<ContactInfoListType2>();
        }
        return this.contactInfoList;
    }

    /**
     * Gets the value of the existingOrder property.
     * 
     * @return
     *     possible object is
     *     {@link ExistingOrderType2 }
     *     
     */
    public ExistingOrderType2 getExistingOrder() {
        return existingOrder;
    }

    /**
     * Sets the value of the existingOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExistingOrderType2 }
     *     
     */
    public void setExistingOrder(ExistingOrderType2 value) {
        this.existingOrder = value;
    }

    /**
     * Gets the value of the fareWaiver property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fareWaiver property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFareWaiver().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FareWaiverType2 }
     * 
     * 
     */
    public List<FareWaiverType2> getFareWaiver() {
        if (fareWaiver == null) {
            fareWaiver = new ArrayList<FareWaiverType2>();
        }
        return this.fareWaiver;
    }

    /**
     * Gets the value of the orderCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link OrderCriteriaType2 }
     *     
     */
    public OrderCriteriaType2 getOrderCriteria() {
        return orderCriteria;
    }

    /**
     * Sets the value of the orderCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderCriteriaType2 }
     *     
     */
    public void setOrderCriteria(OrderCriteriaType2 value) {
        this.orderCriteria = value;
    }

    /**
     * Gets the value of the paxList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paxList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaxList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaxType2 }
     * 
     * 
     */
    public List<PaxType2> getPaxList() {
        if (paxList == null) {
            paxList = new ArrayList<PaxType2>();
        }
        return this.paxList;
    }

    /**
     * Gets the value of the paymentFunctions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentFunctions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentFunctions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentAssociatedFunctionsCriteriaType2 }
     * 
     * 
     */
    public List<PaymentAssociatedFunctionsCriteriaType2> getPaymentFunctions() {
        if (paymentFunctions == null) {
            paymentFunctions = new ArrayList<PaymentAssociatedFunctionsCriteriaType2>();
        }
        return this.paymentFunctions;
    }

    /**
     * Gets the value of the repricedOrder property.
     * 
     * @return
     *     possible object is
     *     {@link RepricedOrderType2 }
     *     
     */
    public RepricedOrderType2 getRepricedOrder() {
        return repricedOrder;
    }

    /**
     * Sets the value of the repricedOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepricedOrderType2 }
     *     
     */
    public void setRepricedOrder(RepricedOrderType2 value) {
        this.repricedOrder = value;
    }

    /**
     * Gets the value of the responseParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responseParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponseParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponseParametersRequestType2 }
     * 
     * 
     */
    public List<ResponseParametersRequestType2> getResponseParameters() {
        if (responseParameters == null) {
            responseParameters = new ArrayList<ResponseParametersRequestType2>();
        }
        return this.responseParameters;
    }

    /**
     * Gets the value of the selectedOffers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedOffers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedOffers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectedOfferType2 }
     * 
     * 
     */
    public List<SelectedOfferType2> getSelectedOffers() {
        if (selectedOffers == null) {
            selectedOffers = new ArrayList<SelectedOfferType2>();
        }
        return this.selectedOffers;
    }

}
