//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Payer Name
 * 
 * <p>Java class for PayerNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayerNameType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="IndividualName" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}PayerIndividualType"/&gt;
 *         &lt;element name="OrganisationName" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}PayerOrganisationType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayerNameType", propOrder = {
    "individualName",
    "organisationName"
})
public class PayerNameType {

    @XmlElement(name = "IndividualName")
    protected PayerIndividualType individualName;
    @XmlElement(name = "OrganisationName")
    protected PayerOrganisationType organisationName;

    /**
     * Gets the value of the individualName property.
     * 
     * @return
     *     possible object is
     *     {@link PayerIndividualType }
     *     
     */
    public PayerIndividualType getIndividualName() {
        return individualName;
    }

    /**
     * Sets the value of the individualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerIndividualType }
     *     
     */
    public void setIndividualName(PayerIndividualType value) {
        this.individualName = value;
    }

    /**
     * Gets the value of the organisationName property.
     * 
     * @return
     *     possible object is
     *     {@link PayerOrganisationType }
     *     
     */
    public PayerOrganisationType getOrganisationName() {
        return organisationName;
    }

    /**
     * Sets the value of the organisationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerOrganisationType }
     *     
     */
    public void setOrganisationName(PayerOrganisationType value) {
        this.organisationName = value;
    }

}
