//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Party committing to pay. In the case of a Credit or Debit Card this would be the Cardholder.
 * 
 * <p>Java class for PayerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PayerEmailAddress" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}EmailAddressType" minOccurs="0"/&gt;
 *         &lt;element name="PayerName" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PayerNameType" minOccurs="0"/&gt;
 *         &lt;element name="PayerPhoneNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PhoneType" minOccurs="0"/&gt;
 *         &lt;element name="PaymentAddress" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PaymentAddressType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayerType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "payerEmailAddress",
    "payerName",
    "payerPhoneNumber",
    "paymentAddress"
})
public class PayerType2 {

    @XmlElement(name = "PayerEmailAddress")
    protected EmailAddressType2 payerEmailAddress;
    @XmlElement(name = "PayerName")
    protected PayerNameType2 payerName;
    @XmlElement(name = "PayerPhoneNumber")
    protected PhoneType2 payerPhoneNumber;
    @XmlElement(name = "PaymentAddress")
    protected PaymentAddressType2 paymentAddress;

    /**
     * Gets the value of the payerEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddressType2 }
     *     
     */
    public EmailAddressType2 getPayerEmailAddress() {
        return payerEmailAddress;
    }

    /**
     * Sets the value of the payerEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddressType2 }
     *     
     */
    public void setPayerEmailAddress(EmailAddressType2 value) {
        this.payerEmailAddress = value;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link PayerNameType2 }
     *     
     */
    public PayerNameType2 getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerNameType2 }
     *     
     */
    public void setPayerName(PayerNameType2 value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the payerPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneType2 }
     *     
     */
    public PhoneType2 getPayerPhoneNumber() {
        return payerPhoneNumber;
    }

    /**
     * Sets the value of the payerPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneType2 }
     *     
     */
    public void setPayerPhoneNumber(PhoneType2 value) {
        this.payerPhoneNumber = value;
    }

    /**
     * Gets the value of the paymentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentAddressType2 }
     *     
     */
    public PaymentAddressType2 getPaymentAddress() {
        return paymentAddress;
    }

    /**
     * Sets the value of the paymentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentAddressType2 }
     *     
     */
    public void setPaymentAddress(PaymentAddressType2 value) {
        this.paymentAddress = value;
    }

}
