//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Payment Time Limit
 * 
 * <p>Java class for PaymentTimeLimitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentTimeLimitType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="PaymentTimeLimitDate" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PaymentTimeLimitDateType"/&gt;
 *         &lt;element name="PaymentTimeLimitDuration" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}PaymentTimeLimitDurationType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentTimeLimitType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "paymentTimeLimitDate",
    "paymentTimeLimitDuration"
})
public class PaymentTimeLimitType2 {

    @XmlElement(name = "PaymentTimeLimitDate")
    protected PaymentTimeLimitDateType2 paymentTimeLimitDate;
    @XmlElement(name = "PaymentTimeLimitDuration")
    protected PaymentTimeLimitDurationType2 paymentTimeLimitDuration;

    /**
     * Gets the value of the paymentTimeLimitDate property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTimeLimitDateType2 }
     *     
     */
    public PaymentTimeLimitDateType2 getPaymentTimeLimitDate() {
        return paymentTimeLimitDate;
    }

    /**
     * Sets the value of the paymentTimeLimitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTimeLimitDateType2 }
     *     
     */
    public void setPaymentTimeLimitDate(PaymentTimeLimitDateType2 value) {
        this.paymentTimeLimitDate = value;
    }

    /**
     * Gets the value of the paymentTimeLimitDuration property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTimeLimitDurationType2 }
     *     
     */
    public PaymentTimeLimitDurationType2 getPaymentTimeLimitDuration() {
        return paymentTimeLimitDuration;
    }

    /**
     * Sets the value of the paymentTimeLimitDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTimeLimitDurationType2 }
     *     
     */
    public void setPaymentTimeLimitDuration(PaymentTimeLimitDurationType2 value) {
        this.paymentTimeLimitDuration = value;
    }

}
