//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Additional Information relating to Payment Cards. For use with PaymentTypeCode(s) relating to Card forms of payment
 * 
 * <p>Java class for PaymentCardAddlInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentCardAddlInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CardProductTypeCode" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="CardTypeText" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}TextType" minOccurs="0"/&gt;
 *         &lt;element name="IIN_IINNumber" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}IIN_NumberType" minOccurs="0"/&gt;
 *         &lt;element name="SecurePaymentAuthenticationVersion" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}SecurePaymentAuthenticationVersionType" minOccurs="0"/&gt;
 *         &lt;element name="VerificationInd" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}IndType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentCardAddlInfoType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "cardProductTypeCode",
    "cardTypeText",
    "iiniinNumber",
    "securePaymentAuthenticationVersion",
    "verificationInd"
})
public class PaymentCardAddlInfoType2 {

    @XmlElement(name = "CardProductTypeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String cardProductTypeCode;
    @XmlElement(name = "CardTypeText")
    protected String cardTypeText;
    @XmlElement(name = "IIN_IINNumber")
    protected String iiniinNumber;
    @XmlElement(name = "SecurePaymentAuthenticationVersion")
    protected SecurePaymentAuthenticationVersionType2 securePaymentAuthenticationVersion;
    @XmlElement(name = "VerificationInd")
    protected Boolean verificationInd;

    /**
     * Gets the value of the cardProductTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardProductTypeCode() {
        return cardProductTypeCode;
    }

    /**
     * Sets the value of the cardProductTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardProductTypeCode(String value) {
        this.cardProductTypeCode = value;
    }

    /**
     * Gets the value of the cardTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTypeText() {
        return cardTypeText;
    }

    /**
     * Sets the value of the cardTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTypeText(String value) {
        this.cardTypeText = value;
    }

    /**
     * Gets the value of the iiniinNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIINIINNumber() {
        return iiniinNumber;
    }

    /**
     * Sets the value of the iiniinNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIINIINNumber(String value) {
        this.iiniinNumber = value;
    }

    /**
     * Gets the value of the securePaymentAuthenticationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link SecurePaymentAuthenticationVersionType2 }
     *     
     */
    public SecurePaymentAuthenticationVersionType2 getSecurePaymentAuthenticationVersion() {
        return securePaymentAuthenticationVersion;
    }

    /**
     * Sets the value of the securePaymentAuthenticationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurePaymentAuthenticationVersionType2 }
     *     
     */
    public void setSecurePaymentAuthenticationVersion(SecurePaymentAuthenticationVersionType2 value) {
        this.securePaymentAuthenticationVersion = value;
    }

    /**
     * Gets the value of the verificationInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerificationInd() {
        return verificationInd;
    }

    /**
     * Sets the value of the verificationInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerificationInd(Boolean value) {
        this.verificationInd = value;
    }

}
