//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ReshopResults
 * 
 * <p>Java class for ReshopResultsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReshopResultsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="NoChangeInd" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}NoChangeIndType"/&gt;
 *         &lt;element name="RepricedOffer" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}RepricedOfferType"/&gt;
 *         &lt;element name="ReshopOffers" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes}ReshopOffersType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReshopResultsType", propOrder = {
    "noChangeInd",
    "repricedOffer",
    "reshopOffers"
})
public class ReshopResultsType {

    @XmlElement(name = "NoChangeInd")
    protected NoChangeIndType noChangeInd;
    @XmlElement(name = "RepricedOffer")
    protected RepricedOfferType repricedOffer;
    @XmlElement(name = "ReshopOffers")
    protected ReshopOffersType reshopOffers;

    /**
     * Gets the value of the noChangeInd property.
     * 
     * @return
     *     possible object is
     *     {@link NoChangeIndType }
     *     
     */
    public NoChangeIndType getNoChangeInd() {
        return noChangeInd;
    }

    /**
     * Sets the value of the noChangeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoChangeIndType }
     *     
     */
    public void setNoChangeInd(NoChangeIndType value) {
        this.noChangeInd = value;
    }

    /**
     * Gets the value of the repricedOffer property.
     * 
     * @return
     *     possible object is
     *     {@link RepricedOfferType }
     *     
     */
    public RepricedOfferType getRepricedOffer() {
        return repricedOffer;
    }

    /**
     * Sets the value of the repricedOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepricedOfferType }
     *     
     */
    public void setRepricedOffer(RepricedOfferType value) {
        this.repricedOffer = value;
    }

    /**
     * Gets the value of the reshopOffers property.
     * 
     * @return
     *     possible object is
     *     {@link ReshopOffersType }
     *     
     */
    public ReshopOffersType getReshopOffers() {
        return reshopOffers;
    }

    /**
     * Sets the value of the reshopOffers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReshopOffersType }
     *     
     */
    public void setReshopOffers(ReshopOffersType value) {
        this.reshopOffers = value;
    }

}
