//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 04:05:01 AM GST 
//


package com.ia.iata.oneorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;


/**
 * A priced grouping of one or more services within an Offer.
 *  The New Offer Item assigns a total price for all included services for all passengers and all segments referenced. Once constructed, the OfferItem cannot be modified.
 * 
 * <p>Java class for SupplierOfferItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierOfferItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AcceptanceRule" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AcceptanceRuleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AirlineTaxonomy" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AirlineTaxonomyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CancelRestrictions" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CancelRestrictionsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ChangeRestrictions" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ChangeRestrictionsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CombinableCarrier" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}InterlineCarrierType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="MandatoryInd" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}IndType" minOccurs="0"/&gt;
 *         &lt;element name="MinimumConnectiontimeDuration" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}DurationType" minOccurs="0"/&gt;
 *         &lt;element name="OfferItemID" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}ID_Type" minOccurs="0"/&gt;
 *         &lt;element name="OfferItemTypeCode" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="OwnerCode" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}AirlineDesigCodeType" minOccurs="0"/&gt;
 *         &lt;element name="OwnerTypeCode" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}OwnerTypeCodeType" minOccurs="0"/&gt;
 *         &lt;element name="Service" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}SupplierOfferedServiceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="StopOverRestrictions" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}StopOverRestrictionsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TotalPrice" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}SupplierPriceType" minOccurs="0"/&gt;
 *         &lt;element name="WebAddressURI" type="{http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional}URI_Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierOfferItemType", namespace = "http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypesFullyOptional", propOrder = {
    "acceptanceRule",
    "airlineTaxonomy",
    "cancelRestrictions",
    "changeRestrictions",
    "combinableCarrier",
    "mandatoryInd",
    "minimumConnectiontimeDuration",
    "offerItemID",
    "offerItemTypeCode",
    "ownerCode",
    "ownerTypeCode",
    "service",
    "stopOverRestrictions",
    "totalPrice",
    "webAddressURI"
})
public class SupplierOfferItemType2 {

    @XmlElement(name = "AcceptanceRule")
    protected List<AcceptanceRuleType2> acceptanceRule;
    @XmlElement(name = "AirlineTaxonomy")
    protected List<AirlineTaxonomyType2> airlineTaxonomy;
    @XmlElement(name = "CancelRestrictions")
    protected List<CancelRestrictionsType2> cancelRestrictions;
    @XmlElement(name = "ChangeRestrictions")
    protected List<ChangeRestrictionsType2> changeRestrictions;
    @XmlElement(name = "CombinableCarrier")
    protected List<InterlineCarrierType2> combinableCarrier;
    @XmlElement(name = "MandatoryInd")
    protected Boolean mandatoryInd;
    @XmlElement(name = "MinimumConnectiontimeDuration")
    protected Duration minimumConnectiontimeDuration;
    @XmlElement(name = "OfferItemID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String offerItemID;
    @XmlElement(name = "OfferItemTypeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String offerItemTypeCode;
    @XmlElement(name = "OwnerCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ownerCode;
    @XmlElement(name = "OwnerTypeCode")
    @XmlSchemaType(name = "token")
    protected OwnerTypeCodeContentType2 ownerTypeCode;
    @XmlElement(name = "Service")
    protected List<SupplierOfferedServiceType2> service;
    @XmlElement(name = "StopOverRestrictions")
    protected List<StopOverRestrictionsType2> stopOverRestrictions;
    @XmlElement(name = "TotalPrice")
    protected SupplierPriceType2 totalPrice;
    @XmlElement(name = "WebAddressURI")
    @XmlSchemaType(name = "anyURI")
    protected String webAddressURI;

    /**
     * Gets the value of the acceptanceRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acceptanceRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcceptanceRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcceptanceRuleType2 }
     * 
     * 
     */
    public List<AcceptanceRuleType2> getAcceptanceRule() {
        if (acceptanceRule == null) {
            acceptanceRule = new ArrayList<AcceptanceRuleType2>();
        }
        return this.acceptanceRule;
    }

    /**
     * Gets the value of the airlineTaxonomy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the airlineTaxonomy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAirlineTaxonomy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirlineTaxonomyType2 }
     * 
     * 
     */
    public List<AirlineTaxonomyType2> getAirlineTaxonomy() {
        if (airlineTaxonomy == null) {
            airlineTaxonomy = new ArrayList<AirlineTaxonomyType2>();
        }
        return this.airlineTaxonomy;
    }

    /**
     * Gets the value of the cancelRestrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cancelRestrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCancelRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CancelRestrictionsType2 }
     * 
     * 
     */
    public List<CancelRestrictionsType2> getCancelRestrictions() {
        if (cancelRestrictions == null) {
            cancelRestrictions = new ArrayList<CancelRestrictionsType2>();
        }
        return this.cancelRestrictions;
    }

    /**
     * Gets the value of the changeRestrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeRestrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangeRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangeRestrictionsType2 }
     * 
     * 
     */
    public List<ChangeRestrictionsType2> getChangeRestrictions() {
        if (changeRestrictions == null) {
            changeRestrictions = new ArrayList<ChangeRestrictionsType2>();
        }
        return this.changeRestrictions;
    }

    /**
     * Gets the value of the combinableCarrier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the combinableCarrier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCombinableCarrier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterlineCarrierType2 }
     * 
     * 
     */
    public List<InterlineCarrierType2> getCombinableCarrier() {
        if (combinableCarrier == null) {
            combinableCarrier = new ArrayList<InterlineCarrierType2>();
        }
        return this.combinableCarrier;
    }

    /**
     * Gets the value of the mandatoryInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMandatoryInd() {
        return mandatoryInd;
    }

    /**
     * Sets the value of the mandatoryInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMandatoryInd(Boolean value) {
        this.mandatoryInd = value;
    }

    /**
     * Gets the value of the minimumConnectiontimeDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMinimumConnectiontimeDuration() {
        return minimumConnectiontimeDuration;
    }

    /**
     * Sets the value of the minimumConnectiontimeDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMinimumConnectiontimeDuration(Duration value) {
        this.minimumConnectiontimeDuration = value;
    }

    /**
     * Gets the value of the offerItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferItemID() {
        return offerItemID;
    }

    /**
     * Sets the value of the offerItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferItemID(String value) {
        this.offerItemID = value;
    }

    /**
     * Gets the value of the offerItemTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferItemTypeCode() {
        return offerItemTypeCode;
    }

    /**
     * Sets the value of the offerItemTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferItemTypeCode(String value) {
        this.offerItemTypeCode = value;
    }

    /**
     * Gets the value of the ownerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerCode() {
        return ownerCode;
    }

    /**
     * Sets the value of the ownerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerCode(String value) {
        this.ownerCode = value;
    }

    /**
     * Gets the value of the ownerTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerTypeCodeContentType2 }
     *     
     */
    public OwnerTypeCodeContentType2 getOwnerTypeCode() {
        return ownerTypeCode;
    }

    /**
     * Sets the value of the ownerTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerTypeCodeContentType2 }
     *     
     */
    public void setOwnerTypeCode(OwnerTypeCodeContentType2 value) {
        this.ownerTypeCode = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplierOfferedServiceType2 }
     * 
     * 
     */
    public List<SupplierOfferedServiceType2> getService() {
        if (service == null) {
            service = new ArrayList<SupplierOfferedServiceType2>();
        }
        return this.service;
    }

    /**
     * Gets the value of the stopOverRestrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopOverRestrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopOverRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StopOverRestrictionsType2 }
     * 
     * 
     */
    public List<StopOverRestrictionsType2> getStopOverRestrictions() {
        if (stopOverRestrictions == null) {
            stopOverRestrictions = new ArrayList<StopOverRestrictionsType2>();
        }
        return this.stopOverRestrictions;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierPriceType2 }
     *     
     */
    public SupplierPriceType2 getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierPriceType2 }
     *     
     */
    public void setTotalPrice(SupplierPriceType2 value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the webAddressURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebAddressURI() {
        return webAddressURI;
    }

    /**
     * Sets the value of the webAddressURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebAddressURI(String value) {
        this.webAddressURI = value;
    }

}
